package com.stromblex.vartapack.report;

import com.stromblex.vartapack.VartaPack;
import com.stromblex.vartapack.api.EnvironmentInfo;
import com.stromblex.vartapack.api.ModInfo;
import com.stromblex.vartapack.api.Platform;
import com.stromblex.vartapack.check.CheckResult;
import com.stromblex.vartapack.config.PackProfile;
import com.stromblex.vartapack.config.VartaConfig;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;

/**
 * Renders a privacy-friendly, copy-pasteable Markdown report.
 * No network calls, no automatic uploads.
 */
public final class SupportReportBuilder {

    /** Optional companion mod id mentioned in the report. */
    public static final String PACKPING_ID = "packping";

    public SupportReport build(Platform platform, VartaConfig config, PackProfile profile,
                               List<CheckResult> results) {
        PrivacyRedactor redactor = new PrivacyRedactor(config.redactUserHomePath(), config.redactUsername());
        EnvironmentInfo env = EnvironmentInfo.capture(platform);

        int crit = 0, err = 0, warn = 0, info = 0;
        for (CheckResult r : results) {
            switch (r.severity()) {
                case CRITICAL -> crit++;
                case ERROR -> err++;
                case WARNING -> warn++;
                case INFO -> info++;
            }
        }

        StringBuilder sb = new StringBuilder(2048);
        sb.append("# VartaPack Support Report\n\n");

        sb.append("## Pack\n");
        sb.append("- Pack name: ").append(safe(profile.packName())).append('\n');
        sb.append("- Pack ID: ").append(safe(profile.packId())).append('\n');
        sb.append("- Profile version: ").append(safe(profile.profileVersion())).append('\n');
        if (!profile.supportUrl().isBlank()) {
            sb.append("- Support URL: ").append(profile.supportUrl()).append('\n');
        }
        sb.append('\n');

        sb.append("## Environment\n");
        sb.append("- Minecraft: ").append(env.minecraftVersion()).append('\n');
        sb.append("- Loader: ").append(env.loaderName()).append('\n');
        sb.append("- Loader version: ").append(env.loaderVersion()).append('\n');
        sb.append("- Java: ").append(env.javaVersion()).append(" (major ").append(env.javaMajor()).append(")\n");
        sb.append("- OS: ").append(env.osName()).append(' ').append(env.osVersion()).append('\n');
        sb.append("- Allocated RAM: ").append(env.maxMemoryMb()).append(" MB\n");
        sb.append("- Game directory: ").append(redactor.redact(env.gameDirectory())).append('\n');
        sb.append('\n');

        sb.append("## Summary\n");
        sb.append("- Critical: ").append(crit).append('\n');
        sb.append("- Errors: ").append(err).append('\n');
        sb.append("- Warnings: ").append(warn).append('\n');
        sb.append("- Info: ").append(info).append('\n');
        sb.append('\n');

        sb.append("## Issues\n");
        if (results.isEmpty()) {
            sb.append("_No issues detected._\n\n");
        } else {
            for (CheckResult r : results) {
                sb.append("[").append(r.severity().name()).append("] ")
                        .append(safe(r.title())).append('\n');
                sb.append(redactor.redact(safe(r.message()))).append('\n');
                if (!r.technicalDetails().isBlank()) {
                    sb.append("  details: ").append(redactor.redact(r.technicalDetails())).append('\n');
                }
                sb.append('\n');
            }
        }

        sb.append("## Optional companion mods\n");
        sb.append("- PackPing: ").append(platform.isModLoaded(PACKPING_ID) ? "installed" : "not installed")
                .append('\n');
        sb.append('\n');

        if (config.includeExtraModsInReport()) {
            sb.append("## Extra mods\n");
            CheckResult extra = findByCode(results, "extra.mods");
            if (extra != null && !extra.technicalDetails().isBlank()) {
                for (String token : extra.technicalDetails().split(", ")) {
                    sb.append("- ").append(token).append('\n');
                }
            } else {
                sb.append("- (none)\n");
            }
            sb.append('\n');
        }

        if (config.includeInstalledModsInReport()) {
            sb.append("## Installed mods\n");
            List<ModInfo> mods = platform.getInstalledMods();
            mods.sort(Comparator.comparing(m -> m.id() == null ? "" : m.id()));
            for (ModInfo m : mods) {
                sb.append("- ").append(safe(m.id())).append(' ').append(safe(m.version())).append('\n');
            }
            sb.append('\n');
        }

        sb.append("---\n");
        sb.append("Generated by ").append(VartaPack.MOD_NAME).append(' ').append(VartaPack.MOD_VERSION);
        sb.append(" at ").append(OffsetDateTime.now(ZoneOffset.UTC).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME));
        sb.append('\n');

        return new SupportReport(sb.toString(), crit, err, warn, info);
    }

    private static String safe(String s) { return s == null ? "" : s; }

    private static CheckResult findByCode(List<CheckResult> list, String code) {
        for (CheckResult r : list) {
            if (code.equals(r.code())) return r;
        }
        return null;
    }
}
