modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/stromblex/VartaPack/issues"

[[mods]]
modId = "vartapack"
version = "${version}"
displayName = "VartaPack"
description = '''
A support report and diagnostics tool for Minecraft modpack authors.
'''
authors = "stromblex"
logoFile = "assets/vartapack/icon.png"
displayURL = "https://github.com/stromblex/VartaPack"

[[dependencies.vartapack]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.vartapack]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"
